# see https://jupyterbook.org/customize/config.html
title: Starccato-JAX
author: starccato devs
#logo: logo.png

execute:
  execute_notebooks: 'off'



repository:
  url: https://github.com/starccato/starccato_jax
  path_to_book: docs
  branch: main

html:
  use_issues_button: true
  use_repository_button: true


sphinx:
  extra_extensions:
    - sphinx.ext.autodoc
